/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ColorText {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLColorTextElement extends Components.ColorText, HTMLStencilElement {
    }
    var HTMLColorTextElement: {
        prototype: HTMLColorTextElement;
        new (): HTMLColorTextElement;
    };
    interface HTMLElementTagNameMap {
        "color-text": HTMLColorTextElement;
    }
}
declare namespace LocalJSX {
    interface ColorText {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "color-text": ColorText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-text": LocalJSX.ColorText & JSXBase.HTMLAttributes<HTMLColorTextElement>;
        }
    }
}
